version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    secrets:
      - db-password
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    container_name: db
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=asteroidsdb
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
volumes:
  db-data:
  mq-data:
secrets:
  db-password:
    file: password.txt
